# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damatex_overseas_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarousalImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to='carousal/')),
            ],
        ),
    ]
