# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damatex_overseas_app', '0002_carousalimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousalimages',
            name='name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
