# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damatex_overseas_app', '0003_carousalimages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousalimages',
            name='image_name',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
