# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
